application: gymmemoserver
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /js
  static_dir: public_html/js
- url: /css
  static_dir: public_html/css
- url: /img
  static_dir: public_html/img
- url: /manifest
  static_dir: public_html/manifest
  mime_type: text/cache-manifest
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
